- name: disable the noddejs
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: enable the nodejs:20
  ansible.builtin.command: "dnf module enable nodejs:20 -y"


- name: install the nodejs
  ansible.builtin.dnf:
    name: "{{item}}"
    state: latest
  loop:
  - nodejs
  - mysql


- name: add the user
  ansible.builtin.user:
    name: expense

- name: create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the  code and unzip the code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes

- name: copy the code
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  notify: deamon reload

