- name: install mysql-server
  ansible.builtin.dnf:
      name: mysql-server
      state: latest

- name: enable and start service
  ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

- name: install the python dependencies
  ansible.builtin.pip:
    name:
      - pymsql
      - cryptography
      executable: pip3.9 

- name: check password is set or not
  community.mysql.mysql_info:
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    filter: version
  register: mysql_info
  ignore_errors: True


- name: print the  mysql_info information
  ansible.builtin.debug:
    msg: "output of {{mysql_info}}"

- name: set the password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{login_password}}"
  when: "output of {{mysql_info}}.failed  is true"


